In [1]:
import networkx as nx

In [78]:
G = nx.read_gml('../../local_resources/political_blogs/polblogs.gml')

In [79]:
nodes = G.nodes()

In [80]:
X = nx.adjacency_matrix(G.to_undirected(), nodes)

In [81]:
X.sum(axis=1)

matrix([[21],
        [16],
        [45],
        ..., 
        [17],
        [33],
        [ 3]])

In [82]:
X.sum(axis=0)

matrix([[21, 16, 45, ..., 17, 33,  3]])

In [83]:
def check_symmetric(a, tol=1e-8):
    return np.allclose(a, a.T, atol=tol)

In [84]:
check_symmetric(X.todense(), tol=1e-8)

True

In [58]:
def prune_disconnected(X, y):
    """
    remove vertices that have no edges from the label and adjacency matrices
    :param X: adj mat
    :param y: labels
    :return:
    """
    keep = np.where(X.sum(axis=1) > 0)[0]
    Xkeep = X[keep, :]
    Xkeep = Xkeep[:, keep]
    try:
        ykeep = y[keep, :]
    except IndexError:
        ykeep = y[keep]
    return Xkeep, ykeep

In [59]:
sum(X.sum(axis=1)==0)

matrix([[425]])

In [60]:
keep = np.where(X.sum(axis=1) > 0)[0]
Xkeep = X[keep, :]
Xkeep = Xkeep[:, keep]

In [61]:
sum(Xkeep.sum(axis=1)==0)

matrix([[32]])

In [54]:
sums1 = X.sum(axis=0)

In [55]:
type(sums1)

numpy.matrixlib.defmatrix.matrix

In [57]:
assert(sums1.all() == sums.all())

In [10]:
y = nx.get_node_attributes(G, 'value')

In [13]:
ids = nx.get_node_attributes(G, 'id')

In [25]:
yarr = [v for k,v in y.iteritems()]

In [29]:
nodes = [k for k,v in y.iteritems()]

In [31]:
X1 = nx.adjacency_matrix(G, nodes)

In [37]:
np.allclose(X.A, X1.A)

False

In [91]:
walks = pd.read_csv('walks_n1_l10.csv', header=None)

In [92]:
walks.head()

0     1     2     3    4    5     6     7     8    9
0   594  1081  1221   765  679  853   237  1121   792  777
1  1122  1092   112  1207  654  607   602   193   850  979
2   819   193   995   992  457  320  1120   670  1120  140
3  1145   436  1145   507  389  460   636   697   535  187
4   260   820  1032   652  209  739   216   912   923  320

In [93]:
ls

X.p                     political_blogs16.emd   political_blogs8.emd
embeddings/             political_blogs2.emd    walks_n1_l10.csv
polblogs.gml            political_blogs32.emd   y.p
polblogs.txt            political_blogs4.emd
political_blogs128.emd  political_blogs64.emd


In [95]:
emd = pd.read_csv('political_blogs2.emd', header=None, index_col=0, skiprows=1, sep=" ")

In [96]:
ls

X.p                     political_blogs16.emd   political_blogs8.emd
embeddings/             political_blogs2.emd    walks_n1_l10.csv
polblogs.gml            political_blogs32.emd   y.p
polblogs.txt            political_blogs4.emd
political_blogs128.emd  political_blogs64.emd


In [97]:
cd ../../src/python/

/Users/workspace/Hyperbolic-Embedding/src/python


In [99]:
path = '../../local_resources/adjnoun/adjnoun.gml'
G = nx.read_gml(path)

NetworkXError: cannot tokenize u'graph' at (2, 1)

In [100]:
def make_one_hot(X):
    """
    Take a vector of integers and convert to one-hot. Assumes continguoes integer labels
    :param X: A 1d numpy integer array of shape (ndata)
    :return: a 2d numpy binary array of shape (ndate, nclasses)
    """
    nclasses = X.max()
    ndata = len(X)
    one_hot = np.zeros(shape=(ndata, nclasses))
    one_hot[range(ndata), X] = 1
    return one_hot

In [102]:
make_one_hot(np.array([1,2,3,4,1]))

IndexError: index 4 is out of bounds for axis 1 with size 4

In [103]:
import cPickle

In [104]:
cPickle.__version__

'1.71'

In [105]:
ls

experiments.py             preprocessing.py
graph.py                   preprocessing.pyc
hyperbolic_embedding.py    run_detectors.py
hyperbolic_embedding.pyc   run_detectors.pyc
multilabel_detectors.py    sample_network.py
multilabel_detectors.pyc   test.py
multilabel_evaluation.py   utils.py
multilabel_evaluation.pyc  utils.pyc
polar_embedding.py         visualisation.py
polar_embedding.pyc        visualisation.pyc


In [106]:
cd ../../local_resources/polbooks/

/Users/workspace/Hyperbolic-Embedding/local_resources/polbooks


In [110]:
cd ../../src/python/

/Users/workspace/Hyperbolic-Embedding/src/python


In [111]:
import utils

In [112]:
cd ../../local_resources/polbooks/

/Users/workspace/Hyperbolic-Embedding/local_resources/polbooks


In [113]:
y = utils.read_pickle('y.p')

In [114]:
y.head()

cat
0   n
1   c
2   c
3   c
4   n

In [115]:
y.to_pickle('y_chars.p')

In [116]:
ls

X.p               polbooks128.emd   polbooks4.emd     y.p
embeddings/       polbooks16.emd    polbooks64.emd    y_chars.p
polbooks.gml      polbooks2.emd     polbooks8.emd
polbooks.txt      polbooks32.emd    walks_n1_l10.csv


In [117]:
y['cat'].unique()

array([u'n', u'c', u'l'], dtype=object)

In [118]:
def polbook_map(x):
    if x == 'n':
        return 0
    if x == 'c':
        return 1
    if x == 'l':
        return 2

In [119]:
y['cat'] = y['cat'].apply(polbook_map)

In [120]:
y.head()

cat
0    0
1    1
2    1
3    1
4    0

In [121]:
y.to_pickle('y.p')

In [122]:
pd.version

AttributeError: 'module' object has no attribute 'version'

In [123]:
pd.__version__

u'0.20.1'

In [124]:
ls

X.p               polbooks128.emd   polbooks4.emd     y.p
embeddings/       polbooks16.emd    polbooks64.emd    y_chars.p
polbooks.gml      polbooks2.emd     polbooks8.emd
polbooks.txt      polbooks32.emd    walks_n1_l10.csv


In [125]:
cd ..

/Users/workspace/Hyperbolic-Embedding/local_resources


In [142]:
cd ../src/python/

/Users/workspace/Hyperbolic-Embedding/src/python


In [143]:
reload(utils)

<module 'utils' from 'utils.py'>

In [144]:
cd ../../local_resources/

/Users/workspace/Hyperbolic-Embedding/local_resources


In [152]:
folder = 'football/'
X,y = utils.read_data(folder+'X.p', folder+'y.p', 0)
print max(y) - min(y) + 1
print X.sum()/2
print np.unique(y)
print np.bincount(y)/float(len(y))

input matrix of shape: (115, 115)
output matrix of shape: (115, 115)
(115, 115)
12
613
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0.07826087  0.06956522  0.09565217  0.10434783  0.08695652  0.04347826
  0.11304348  0.06956522  0.08695652  0.10434783  0.06086957  0.08695652]


In [153]:
from scipy.stats import sem

In [154]:
x = np.random.rand(3,4)

In [155]:
x

array([[ 0.57301741,  0.20550785,  0.78087257,  0.58416009],
       [ 0.06927909,  0.52180659,  0.0276796 ,  0.10581303],
       [ 0.42499266,  0.71840419,  0.2123462 ,  0.31553905]])

In [156]:
sem(x, axis=0)

array([ 0.1494798 ,  0.14939845,  0.22664505,  0.13843534])

In [164]:
y = np.linspace(0.1, 0.9, 9)

In [165]:
y*2

array([ 0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8])